[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "STACpopulator"
version = "0.0.1"
requires-python = ">=3.9"

[tool.setuptools]
py-modules = ["STACpopulator"]